// One-shot transform: pull the offkeep phone dataset and rewrite it to be
// self-contained (import CountryCode from ./countries instead of the external
// react-address-tax package). Run with: bun run scripts/gen-phone-data.ts
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SRC = "/Users/iv-stpn/Desktop/offkeep/packages/ui/src/lib/phone/country-phone-data.ts";
const OUT = resolve(import.meta.dir, "../src/data/phone-data.ts");

const raw = readFileSync(SRC, "utf8");

// Drop the offkeep header + external imports/re-exports; we re-add our own.
const bodyStart = raw.indexOf("export type CountryPhoneConfig");
if (bodyStart === -1) throw new Error("Could not locate CountryPhoneConfig in source");

const body = raw.slice(bodyStart);

const header = `// AUTO-GENERATED by scripts/gen-phone-data.ts — do not edit by hand.
// Regenerate with: bun run gen:phone-data
//
// Phone configuration per country (ISO 3166-1 alpha-2). Each entry carries the
// calling code, an input mask, a formatted example, a national-number validation
// regex, and the optional trunk prefix (the leading digit dropped in E.164 form).
import type { CountryCode } from "./countries";

`;

writeFileSync(OUT, header + body, "utf8");
console.log(`Wrote ${OUT} (${(header + body).length} bytes)`);
