// One-shot transform: pull the offkeep phone dataset and rewrite it to be
// self-contained (import CountryCode from ./countries instead of the external
// react-address-tax package). Run with:
//   bun run gen:phone-data <path-to-country-phone-data.ts>
// or set PHONE_DATA_SRC. The source file isn't vendored in this repo.
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SRC = process.argv[2] ?? process.env.PHONE_DATA_SRC;
if (!SRC) {
  console.error(
    "Missing source path. Usage: bun run gen:phone-data <path-to-country-phone-data.ts>\n" +
      "or set the PHONE_DATA_SRC environment variable.",
  );
  process.exit(1);
}
const OUT = resolve(import.meta.dir, "../src/data/phone-data.ts");

const raw = readFileSync(SRC, "utf8");

// Drop the offkeep header + external imports/re-exports; we re-add our own.
const bodyStart = raw.indexOf("export type CountryPhoneConfig");
if (bodyStart === -1) throw new Error("Could not locate CountryPhoneConfig in source");

const body = raw.slice(bodyStart);

const header = `// AUTO-GENERATED by scripts/gen-phone-data.ts — do not edit by hand.
// Regenerate with: bun run gen:phone-data
//
// Phone configuration per country (ISO 3166-1 alpha-2). Each entry carries the
// calling code, an input mask, a formatted example, a national-number validation
// regex, and the optional trunk prefix (the leading digit dropped in E.164 form).
import type { CountryCode } from "./countries";

`;

// Hand-maintained disambiguation data for calling codes shared by several
// countries. Not part of the offkeep source — kept here so it ships with the
// generated dataset, and emitted on every regenerate. Edit below and re-run
// `bun run gen:phone-data`.
const extra = `
// --- Shared-calling-code disambiguation (hand-maintained) -------------------
// Several calling codes are shared by more than one country (e.g. +1 is US,
// Canada and the NANP dependencies; +44 is the UK and its crown dependencies).
// The data below pins the right country for a given national number, falling
// back to a per-code default (the biggest country) when no specific match is
// found. Edited in scripts/gen-phone-data.ts — regenerate to apply changes.

/**
 * For calling codes shared by several countries, the "biggest" country to
 * default to when a number can't be pinned to a specific country (e.g. by area
 * code). Keyed by the calling code exactly as stored on CountryPhoneConfig
 * ("+1"). Without this, the first catalogue entry (alphabetical by ISO code)
 * would win — so a bare "+1" would resolve to Antigua (AG) instead of the US.
 */
export const CALLING_CODE_DEFAULTS: ReadonlyMap<string, CountryCode> = new Map<string, CountryCode>([
  ["+1", "US"],
  ["+7", "RU"],
  ["+39", "IT"],
  ["+44", "GB"],
  ["+47", "NO"],
  ["+61", "AU"],
  ["+64", "NZ"],
  ["+212", "MA"],
  ["+262", "RE"],
  ["+358", "FI"],
  ["+500", "FK"],
  ["+590", "GP"],
  ["+599", "CW"],
  ["+672", "NF"],
]);

/**
 * NANP (+1) area-code -> ISO map. The first three national digits pin the
 * country. US area codes are intentionally absent: they resolve to the +1
 * default (US). Canada and every Caribbean / overseas dependency area code is
 * listed. Maintained by hand — add new Canadian overlay codes as NANP assigns
 * them.
 */
export const NANP_AREA_CODE_TO_COUNTRY: ReadonlyMap<string, CountryCode> = new Map([
  // Canada — every Canadian area code resolves to CA.
  ["204", "CA"], ["226", "CA"], ["236", "CA"], ["249", "CA"], ["250", "CA"],
  ["263", "CA"], ["289", "CA"], ["306", "CA"], ["343", "CA"], ["354", "CA"],
  ["365", "CA"], ["367", "CA"], ["368", "CA"], ["403", "CA"], ["416", "CA"],
  ["418", "CA"], ["428", "CA"], ["431", "CA"], ["437", "CA"], ["438", "CA"],
  ["450", "CA"], ["468", "CA"], ["474", "CA"], ["506", "CA"], ["514", "CA"],
  ["519", "CA"], ["548", "CA"], ["579", "CA"], ["581", "CA"], ["584", "CA"],
  ["587", "CA"], ["604", "CA"], ["613", "CA"], ["639", "CA"], ["647", "CA"],
  ["672", "CA"], ["705", "CA"], ["709", "CA"], ["742", "CA"], ["753", "CA"],
  ["778", "CA"], ["780", "CA"], ["782", "CA"], ["807", "CA"], ["819", "CA"],
  ["825", "CA"], ["867", "CA"], ["873", "CA"], ["879", "CA"], ["902", "CA"],
  ["905", "CA"], ["942", "CA"],

  // Caribbean & overseas dependencies.
  ["242", "BS"], // Bahamas
  ["246", "BB"], // Barbados
  ["264", "AI"], // Anguilla
  ["268", "AG"], // Antigua & Barbuda
  ["284", "VG"], // British Virgin Islands
  ["345", "KY"], // Cayman Islands
  ["340", "VI"], // U.S. Virgin Islands
  ["441", "BM"], // Bermuda
  ["473", "GD"], // Grenada
  ["649", "TC"], // Turks & Caicos Islands
  ["658", "JM"], // Jamaica
  ["664", "MS"], // Montserrat
  ["670", "MP"], // Northern Mariana Islands
  ["671", "GU"], // Guam
  ["684", "AS"], // American Samoa
  ["721", "SX"], // Sint Maarten
  ["758", "LC"], // Saint Lucia
  ["767", "DM"], // Dominica
  ["784", "VC"], // Saint Vincent & the Grenadines
  ["787", "PR"], // Puerto Rico
  ["809", "DO"], // Dominican Republic
  ["829", "DO"], // Dominican Republic
  ["849", "DO"], // Dominican Republic
  ["868", "TT"], // Trinidad & Tobago
  ["869", "KN"], // Saint Kitts & Nevis
  ["876", "JM"], // Jamaica
  ["939", "PR"], // Puerto Rico
]);

/**
 * Per-calling-code national-number prefix -> ISO maps, used to tell apart
 * countries that share a calling code by their leading digits (area code). The
 * longest matching prefix wins; if no prefix matches, the CALLING_CODE_DEFAULTS
 * entry for the code is used. Prefixes are only listed where they unambiguously
 * belong to a non-default country (e.g. +44 1481 -> Guernsey; +7 6/7 ->
 * Kazakhstan). Codes whose members share identical number ranges (+590
 * Guadeloupe / St. Martin / St. Barthélemy) are left to the default.
 */
export const CALLING_CODE_AREA_PREFIXES: ReadonlyMap<string, ReadonlyMap<string, CountryCode>> = new Map([
  ["+1", NANP_AREA_CODE_TO_COUNTRY],
  ["+39", new Map([["06698", "VA"]])], // Vatican City (Rome 06 698 block)
  ["+44", new Map([["1481", "GG"], ["1534", "JE"], ["1624", "IM"]])], // Guernsey / Jersey / Isle of Man
  ["+47", new Map([["79", "SJ"]])], // Svalbard & Jan Mayen
  ["+212", new Map([["528", "EH"]])], // Western Sahara (Laâyoune)
  ["+262", new Map([["639", "YT"]])], // Mayotte
  ["+358", new Map([["18", "AX"]])], // Åland Islands
  ["+599", new Map([["31", "BQ"], ["41", "BQ"], ["7", "BQ"]])], // Bonaire / Saba / Sint Eustatius (Curaçao is the +599 default)
  ["+672", new Map([["1", "AQ"]])], // Australian Antarctic (Norfolk Island is the +672 default)
  ["+7", new Map([["6", "KZ"], ["7", "KZ"]])], // Kazakhstan (Russia is the +7 default)
]);
`;

writeFileSync(OUT, header + body + extra, "utf8");
console.log(`Wrote ${OUT} (${(header + body + extra).length} bytes)`);
